import random

class DailyQuotes:
  @staticmethod
  def get_random_quote():
    quote_list = [
      'Veni, vidi, vici.',
      'Et tu, Brute?',
      'The best revenge is to be unlike him who performed the injury.',
      'Carthago delenda est.',
      'Fortune favors the bold.',
      'While they teach, they learn.',
      'In wine, there is truth.',
      'As is a tale, so is life: not how long it is, but how good it is, is what matters.',
      'I found Rome a city of bricks and left it a city of marble.',
      'Brave men are a city\'s strongest tower of defense.',
      'If you want peace, prepare for war.',
      'To err is human.',
      'Waste no more time arguing what a good man should be. Be one.',
      'Laws are silent in times of war.',
      'Endurance is the crowning quality.',
      'A room without books is like a body without a soul.',
      'Bread and circuses.',
      'Carpe diem.',
      'Love conquers all things; let us too surrender to love.',
      'History is the teacher of life.',

      'All warfare is based on deception.',
      'Knowing others is intelligence; knowing yourself is true wisdom.',
      'The supreme art of war is to subdue the enemy without fighting.',
      'A journey of a thousand miles begins with a single step.',
      'He who knows when he can fight and when he cannot, will be victorious.',
      'To see what is right and not do it is a lack of courage.',
      'The ruler is a boat; the people are the water. The water can carry the boat or overturn it.',
      'When the command is clear but not obeyed, it is the fault of the officers.',
      'Great talent takes time to mature.',
      'Treat your men as you would your own beloved sons. And they will follow you into the deepest valley.',
      'One who is too insistent on his own views finds few to agree with him.',
      'In the midst of chaos, there is also opportunity.',
      'The more laws and order are made prominent, the more thieves and robbers there will be.',
      'Opportunities multiply as they are seized.',
      'He who fights and runs away may live to fight another day.',
      'If you are far from the enemy, make him believe you are near.',
      'Nature does not hurry, yet everything is accomplished.',
      'Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.',
      'Be extremely subtle even to the point of formlessness.',
      'There is no greater danger than underestimating your opponent.',

      'I see now that the circumstances of one\'s birth are irrelevant. It is what you do with the gift of life that determines who you are.',
      'To extend our reach to the stars above!',
      'Strong Pokémon. Weak Pokémon. That is only the selfish perception of people.',
      'I’m gonna be the world’s greatest Pokémon Master!',
      'Even if we don\'t understand each other, that\'s not a reason to reject each other.',
      'There are bad ways to win—and good ways to lose. What’s interesting and troubling is that it’s not always clear which is which.',
      'A champion is a person who has dedicated themselves to their dream.',
      'Pikachu, I choose you!',
      'Take a chance and you may lose. Take no chance and you have already lost!',
      'The more wonderful the soul, the more it will sparkle.',

      'Nothing in life is to be feared, it is only to be understood.',
      'Imagination is more important than knowledge.',
      'If I have seen further it is by standing on the shoulders of Giants.',
      'Equipped with his five senses, man explores the universe around him and calls the adventure Science.',
      'Somewhere, something incredible is waiting to be known.',
      'Science is not only a disciple of reason but, also, one of romance and passion.',
      'In science, there are no shortcuts to the truth.',
      'The good thing about science is that it\'s true whether or not you believe in it.',
      'A man who dares to waste one hour of time has not discovered the value of life.',
      'Science knows no country, because knowledge belongs to humanity.',

      'Inherited Will, The Destiny of the Age, and The Dreams of the People. As long as people continue to pursue the meaning of Freedom, these things will never cease!',
      'When do you think people die? When they are shot by a pistol? No. It’s when they are forgotten.',
      'Scars on the back are a swordsman\'s shame.',
      'Being alone is more painful than getting hurt.',
      'Pirates are evil? Marines are righteous? These terms have always changed throughout the course of history!',
      'I don\'t want to conquer anything. I just think that the guy with the most freedom in this whole ocean is the Pirate King!',
      'No matter how hard or how impossible it is, never lose sight of your goal.',
      'A man\'s dream will never die!',
      'I want to live!',
      'Thanks... for loving me!',

      'The only thing we have to fear is fear itself.',
      'I have a dream.',
      'Spread love everywhere you go. Let no one ever come to you without leaving happier.',
      'It always seems impossible until it\'s done.',
      'The way to get started is to quit talking and begin doing.',
      'Success is not final, failure is not fatal: it is the courage to continue that counts.',
      'Be the change that you wish to see in the world.',
      'The greatest glory in living lies not in never falling, but in rising every time we fall.',
      'Your time is limited, so don\'t waste it living someone else\'s life.',
      'I think, therefore I am.',

      'Whatever you lose, you\'ll find it again. But what you throw away you\'ll never get back.',
      'I am the hope of the universe. I am the answer to all living things that cry out for peace.',
      'Equivalent Exchange: To obtain something, something of equal value must be lost.',
      'If you don\'t like your destiny, don\'t accept it. Instead, have the courage to change it.',
      'Human beings are strong because we can change ourselves.',
      'Fear is not evil. It tells you what your weakness is.',
      'I’ll take a potato chip... AND EAT IT!',
      'I have no house to go back to. In this world, the only place I can return to is you.',
      'Omae wa mou shindeiru.',
      'The world isn\'t perfect. But it\'s there for us, doing the best it can.',
    
      'An eye for an eye makes the whole world blind.',
      'When the power of love overcomes the love of power, the world will know peace.',
      'The only true wisdom is in knowing you know nothing.',
      'Happiness is not something ready-made. It comes from your own actions.',
      'Out of the mountain of despair, a stone of hope.',
      'To be, or not to be, that is the question.',
      'Knowledge is power.',
      'He who has a why to live can bear almost any how.',
      'Life is what happens when you\'re busy making other plans.',
      'Man is born free, and everywhere he is in chains.',
    ]
    return random.choice(quote_list)
  
class MultiColor:
  pass

class SoundBoard:
  @staticmethod
  def trigger_click_sound():
    print('[SYSTEM]: Mechanical Switch Sound Triggered.')